name: Run quick tests
on:
  push:
    branches:
      - '**'

jobs:
  composer-audit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Composer install
        run: composer install --dev

      - name: Run Composer audit
        run: composer audit

  unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Composer install
        run: composer install --dev

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testsuite unit --testdox

  static-code-analysis:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Composer install
        run: composer install --dev

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=-1

  coding-standards:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Composer install
        run: composer install --dev

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs -p
