name: Run quick tests
on:
  push:
    branches:
      - '**'

jobs:
  composer-audit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose up -d

      - name: Run Composer audit
        run: docker-compose exec -T app composer audit

      - name: Stop containers
        run: docker-compose down -v

  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose up -d

      - name: Run PHPUnit
        run: docker-compose exec -T app vendor/bin/phpunit --testsuite unit --testdox

      - name: Stop containers
        run: docker-compose down -v

  static-code-analysis:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose up -d

      - name: Run PHPStan
        run: docker-compose exec -T app vendor/bin/phpstan analyse --memory-limit=-1

      - name: Stop containers
        run: docker-compose down -v

  coding-standards:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PHP CodeSniffer
        run: docker-compose exec -T app vendor/bin/phpcs src tests --colors

      - name: Stop containers
        run: docker-compose down -v
